# Generated by Django 5.2.4 on 2025-07-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
